### ISSUE TITLE
Add conditional exports

### ISSUE THREAD

**Issue by dandv** [lukeed/typescript-module#1]
Thanks for this template! The only issue I've run into while using it was that I couldn't use name imports from transpiled ESM code (`"module": "esnext"` in `tsconfig.json`). The error ([seen by others in similar situations](https://github.com/apollographql/apollo-server/issues/1356#issuecomment-681313954)) was,

> The requested module '...' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.

I've solved that in my package [`local-iso-dt`](https://github.com/dandv/local-iso-dt) by using [conditional exports](https://nodejs.org/api/esm.html#esm_conditional_exports) ([diff](https://github.com/dandv/local-iso-dt/commit/00d02af5fcaf06ca17c3f2b9e86f44ddc174b628)).

**Comment by lukeed** [comment]
Added, thank you for the reminder :) I think I was still on-the-fence about the `exports` landscape, but I think enough time has passed to make me feel like it's safe to just provide it as a default.
