### ISSUE TITLE
Rollup external: object vs array

### ISSUE THREAD

**Issue by vimbrandt** [lukeed/typescript-module#2]
Hello 👋 

Currently the value of `external` in `rollup.config.js` is an object literal, but it looks like it should be an array.

[Reference](https://rollupjs.org/guide/en/#external)

Switching the `{ }` to `[ ]` fixed the bug I had with external modules while using this template.

Cheers!

**Comment by lukeed** [comment]
Oh, oops! Definitely should be an array. I'll happily accept a PR if you don't mind sending one
